language: node_js
node_js:
- '7'
addons:
  code_climate:
    repo_token:
      secure: gDor5U77U8siSz0bnHJ5pfFGVi6XsFEgHqgz5mYdkVenFc6LfeIJo+sXb49IAhTKjeMQ1iomDb6K/xM46PY3x5O0wuSfzEkcryDpaK/z3Oq4QLdSNiKdBf6wbBhRe28DckXVoI+bQypFLrMk9jvTWeSnfCCLAzKfptd6O9fbomqN8vNOC3egDxd8zTuWjGIICnJ5Nq7vVn4cLaw5+N21jrwrszu/uctRXYQDsY8pCFIyukovgE3KzsnipOr8LImj5lbL1sCeaqmACxRCwKFGQuwMLMLyOI1gHcgAjK+GqDnDTNAxiMUVqpyztnUKWOfc1aS0c3qGWv4eX+thpkpxvME1v/Zd4eBVfuoIpMhEGAjJWBhTKfBo0JI8HuMpMwQW4qRNRe5fYm4sWBdbzR/ylziU2QTtDiGcpp6PGEd9BphjXjD9SLOk4aXL/+D00SnYJ3OMCWRnXa9cKdvaSCXH3adyk/YWo9XXxrRyYUrMIvMUzXA0fNODLf6/UH0l/KR2FQ0MCaCJJUcD67g5PbIG+vYtRD2oTj/RVSVgeicxT4bOtyv55sBgjt9Z/uEtAJoe6sqduTH9lYej0koA7qRYGufEylDE2LOnLJf4cfqJvmX883ZYbjT9IkhwqDFgZE7YKqmBFmhdBJRB9MDCCYl3gwx/8lc82f0Xq5XZBo2+vhg=
deploy:
  provider: npm
  email: n.moraes.dantas@gmail.com
  api_key: $NPM_API_KEY
cache:
  directories:
  - node_modules
before_install:
- npm rm --save-dev
- test ! -d node_modules || npm prune
- test ! -d node_modules || npm rebuild
script: npm run-script test-ci
after_script: npm install coveralls && cat ./coverage/lcov.info | coveralls
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < ./coverage/lcov.info
