language: node_js
node_js:
  - "7"
addons:
  code_climate:
    repo_token: 92bed136c018a8e2118fbebbe89fa95ad9ded941704fb55f3af002ee99980cc5
cache:
  directories:
    - node_modules
before_install:
  # Remove all non-test dependencies
  - "npm rm --save-dev"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script: "npm run-script test-ci"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
